spring.application.name=pillpal-backend
server.port=8080
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

frontend.url=${FRONTEND_URL}

# JWT Config
jwt.secret=${JWT_SECRET}
jwt.access.expiration=86400000
jwt.refresh.expiration=2592000000
