server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=harsha
spring.datasource.password=harsha
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Config
jwt.secret=K2n8vRz5wQp9Xf6Lk3Tj1Uy7Sd4Vb8NmGh2Pq5Rf0Xy6Zl1A
jwt.access.expiration=86400000
jwt.refresh.expiration=2592000000